### ISSUE TITLE
Setup E2E test framework

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas.Auto.Tests#1]
## Notes
- The current plan is that E2E tests will point to an existing instance of Atlas, most likely dev to begin with.
- Therefore, they currently do not need their own Atlas infrastructure.

## Task list
- [x] Create new repo for Atlas E2E tests
- [x] Create test framework with one test that calls one of the debug endpoints and confirms an OK result
- [x] Define new pipeline to run tests via DevOps
- [x] Enhance  pipeline to allow running of multiple job categories in parallel
- [x] Add HTML reporting to pipeline
